# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getQuantileCpp <- function(FY, kI, kU) {
    .Call(`_ptse_getQuantileCpp`, FY, kI, kU)
}

predCFCpp <- function(FY1XWpred, QY1XCF, itrY, itrU, weights, nGridsFine, n, weighted, discY) {
    .Call(`_ptse_predCFCpp`, FY1XWpred, QY1XCF, itrY, itrU, weights, nGridsFine, n, weighted, discY)
}

predQ1Cpp <- function(FY1Wpred, FY0Wpred, itrY, itrU, nGridsFine, n, discY, UB) {
    .Call(`_ptse_predQ1Cpp`, FY1Wpred, FY0Wpred, itrY, itrU, nGridsFine, n, discY, UB)
}

